language: python
before_script:
- pip install --no-use-wheel --no-cache-dir cython
python:
- 3.5.2
script: coverage run setup.py test
after_success:
- codecov
deploy:
  provider: pypi
  user: muhammedhasan
  password:
    secure: JUFvOBv8xAbSHDtV8kmtUxsHOInIIxM/1z7I4Fv/kKnj5VHxBuIZPWqTfzNDPZITM5AyWzbD04ygJBYUzX0+UBPmr+/rs0yhAxzP8fFoTobU7FXQ+OcWfHPGFfiL1YNxKcuQ0IPC9RZrfHzTeExKtxBODlBMs/ncTBCVqF2hfAQzZ9iZoziEfxFFg938fPqjE4Ep+Bw7FdEG47RsYN3A0w0WSk81b6qvVtLeqAPEMjjwZrN4os03RjJYgjWc3Hr9JCFdkGZ6fBrJ75ATBXwAFlhPCavnPeOeewU6OYPVCJKSOpmdXl6emtpzj+Zi9Kk4rU+8GPUHpAdmOzsC1GVR1z5zCmUI4tvFGMGaghYKtXcGEE+X5V0PjFMeVeTh3+ebkZY69XCapuiR8yHdvCdx44/yvQ2Lb7bJ76xRd8JBHd7AsjU+bjXdFWcORSwuteWsV8q86bYz1tC++gFQJhs5BTwmnEM20dTpBEnTm+57XxkxKTRjwWGzdZP+V5VdybjWXjvtVN271EhE3VO7y1/7ERfnH8bNuVCfyVTPpy5g7miCvCUAAyBTfNlOCeji3vNgHSD6uZzLR5oH0PuWfGrbUdZAprLRxC2qTMMS2TpAWS75oQUQLCaB4jZNlfIMj8Y400+j7gNpQzcaOqvLk3oTm+98DR1sspdlP3Tj35EwedU=
  on:
    branch: master
