language: python

before_script: 

python:
  - 3.5.2

script: coverage run setup.py test

after_success:
- codecov

deploy:
  provider: pypi
  user: muhammedhasan
  password:
    secure: t5sibi/4gXHQwsw+8LAsJebXRo2s0vAvCMm8NvLRKCXFSUoh+BBb7BfGj7ewNPkZfbu1SEB1xqux1RLGGeQxx+ZP0UPOio4CbxU0LjEZfa+CBZXnwM8OntYTp5RIUebuF7kmWBurGYBQMBlMnvXNH7FGCCbOSSDUhXTMT6ZnJ8tJZHn5ScNUNzULyL57Vg3psdIfhzespNSDZr8qtn5KaGM79LiDaIlcuLS9Rcf+rX/ALbeZsCEXsuxtItooRCk1SljC0t3NXXtYxeOmVy3hz7Ej91be9RdAak5ek0p4XVKozviLczxfciKhAJsRTpMICXDq1448sCTyaufsga9R3cS6i5Shbt8CRsR5WZhDTWgS+rf21VQ/6dpBXWYRXf9uGaVeWQHygXSHgKGFrULLDHVb3D3DLKqOK+P8p0NmbdkooF/KaBfviwyku+EMwdpVcoGO3T9b9PhCpVWGa9WCqHkakKCLZIXPnR5OGLIFyQquo4DkUkkuchD3hfPEYvu+J4EoDSyN6038cvQl+5tW4MctQzy8WsfJN1hYISen4f9oDzm1XEyRPctfaXr8+6/elnbKZ8ykOuHtnXrQBq+/2dR/tH13iE37bGejRyDyW+HqT6pDHCl/aoT256Vs1tDhUrzbVPLt/2vVKtdyk3zBLAKANR222CjlBsS8FpGOipU=
